# Generated by Django 5.1.3 on 2024-12-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='customer',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
