# Generated by Django 5.1.3 on 2024-12-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_user_book_customer_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='customer',
            new_name='user',
        ),
    ]
